# Generated by Django 2.1 on 2019-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityseapes',
            name='slug',
            field=models.SlugField(default=False, max_length=66),
        ),
        migrations.AddField(
            model_name='nature',
            name='slug',
            field=models.SlugField(default=False, max_length=66),
        ),
        migrations.AddField(
            model_name='portraits',
            name='slug',
            field=models.SlugField(default=False, max_length=66),
        ),
    ]
